**Python Dictionary Methods — Assignment**

**Set A — Warm-up**

*1. Create book = {&quot;title&quot;: &quot;Python Basics&quot;, &quot;price&quot;: 300}. Use update() to add &quot;author&quot;: &quot;Ravi&quot;. Print the dictionary.*

In [3]:
book = {"title": "Python Basics", "price": 300}

book.update({"author": "Ravi"})

print(book)

{'title': 'Python Basics', 'price': 300, 'author': 'Ravi'}


*2. Start with book = {&quot;title&quot;: &quot;Python Basics&quot;, &quot;price&quot;: 300}. In a single update() call, change price to 250 and
add &quot;pages&quot;: 180. Print the dictionary.*

In [4]:
book = {"title": "Python Basics", "price": 300}

book.update({"price": 250, "pages": 180})

print(book)

{'title': 'Python Basics', 'price': 250, 'pages': 180}


*3. Start with book = {&quot;title&quot;: &quot;Python Basics&quot;, &quot;price&quot;: 250, &quot;pages&quot;: 180}. Remove &quot;pages&quot; using pop(). Print
the removed value, then the dictionary.*

In [5]:
book = {"title": "Python Basics", "price": 250, "pages": 180}

removed = book.pop("pages")

print("Removed value:", removed)
print("Dictionary:", book)

Removed value: 180
Dictionary: {'title': 'Python Basics', 'price': 250}


*4. Create a dictionary with 3 items: fruits = {&quot;apple&quot;: 50, &quot;banana&quot;: 30, &quot;mango&quot;: 20}. Use popitem() and
print the removed pair and the remaining dictionary.*

In [6]:
fruits = {"apple": 50, "banana": 30, "mango": 20}

removed = fruits.popitem()

print("Removed pair:", removed)
print("Remaining dictionary:", fruits)

Removed pair: ('mango', 20)
Remaining dictionary: {'apple': 50, 'banana': 30}


*5. Make a copy of a dictionary, clear() the original, then print both.*

In [7]:
fruits = {"apple": 50, "banana": 30, "mango": 20}

removed = fruits.popitem()

print("Removed pair:", removed)
print("Remaining dictionary:", fruits)

Removed pair: ('mango', 20)
Remaining dictionary: {'apple': 50, 'banana': 30}


*6. Predict the output without running it:*

d = {&quot;a&quot;: 1, &quot;b&quot;: 2, &quot;c&quot;: 3}

d.pop(&quot;b&quot;)

d.popitem()

print(d)

In [8]:
d = {"a": 1, "b": 2, "c": 3}

d.pop("b")
d.popitem()

print(d)

{'a': 1}


**Set B — Apply It**

*1. A shop has stock = {&quot;apple&quot;: 50, &quot;banana&quot;: 30, &quot;mango&quot;: 20}. Using one update(), set apple to 45 and add
&quot;orange&quot;: 25. Print the stock.*

In [1]:
stock = {"apple": 50, "banana": 30, "mango": 20}

stock.update({"apple": 45, "orange": 25})

print(stock)

{'apple': 45, 'banana': 30, 'mango': 20, 'orange': 25}


*2. Ask the user for a key to delete from a dictionary. Use pop() with a default value so the program prints
either the removed value or &quot;Key not found&quot;. It must never crash.*


In [2]:
student = {
    "name": "Rahul",
    "age": 21,
    "course": "Python"
}

key = input("Enter key to delete: ")

removed = student.pop(key, "Key not found")

if removed == "Key not found":
    print("Key not found")
else:
    print("Removed value:", removed)

print(student)

Enter key to delete:  key not found


Key not found
{'name': 'Rahul', 'age': 21, 'course': 'Python'}


*3. Merge these using update(), then explain why b changed:*

dict1 = {&quot;a&quot;: 1, &quot;b&quot;: 2}

dict2 = {&quot;b&quot;: 20, &quot;c&quot;: 3}

Expected output: {&#39;a&#39;: 1, &#39;b&#39;: 20, &#39;c&#39;: 3}


In [3]:
dict1 = {"a": 1, "b": 2}
dict2 = {"b": 20, "c": 3}

dict1.update(dict2)

print(dict1)

{'a': 1, 'b': 20, 'c': 3}


*4. The copy trap. Run this and write down the output. Then repeat using b = a.copy() and explain the
difference.*

a = {&quot;x&quot;: 1}

b = a

b[&quot;x&quot;] = 99

print(a)


In [4]:
a = {"x": 1}

b = a

b["x"] = 99

print(a)

{'x': 99}


In [5]:
a = {"x": 1}

b = a.copy()

b["x"] = 99

print(a)
print(b)

{'x': 1}
{'x': 99}


*5. Given marks = {&quot;Maths&quot;: 80, &quot;Science&quot;: 75, &quot;English&quot;: 90}, use a while loop and popitem() to remove and
print items one by one until the dictionary is empty.*



In [9]:
marks = {
    "Maths": 80,
    "Science": 75,
    "English": 90
}
while marks:
    item = marks.popitem()
    print(item)

('English', 90)
('Science', 75)
('Maths', 80)


*6. Make a cart dictionary with 3 items. Take a backup using copy(), then clear() the cart. Print both and print
len() of each.*

In [11]:
cart = {
    "pen": 10,
    "book": 50,
    "bag": 500
}

backup = cart.copy()

cart.clear()

print("Cart:", cart)
print("Backup:", backup)

print("Cart length:", len(cart))
print("Backup length:", len(backup))

Cart: {}
Backup: {'pen': 10, 'book': 50, 'bag': 500}
Cart length: 0
Backup length: 3


**Set C - Challenge**

**5. Shallow copy puzzle**

In [3]:
a = {"name": "John", "marks": [80, 90]}
b = a.copy()
b["marks"].append(100)
b[ "name"] = "Sam"
print (a)
# {'name':"John""marks': [80, 90, 100]}

{'name': 'John', 'marks': [80, 90, 100]}


name is a string. b["name"] = "Sam" rebinds b's key to a new string, so a keeps "John". marks is a list shared by both dictionaries.
append(100) modifies that one list in place, so a sees the change.